// Code generated by qtc from "mainpage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Main page template. Implements BasePage methods.
//

//line ../internal/templates/mainpage.qtpl:3
package templates

//line ../internal/templates/mainpage.qtpl:3
import (
	"github.com/Fedena22/Holiday_bucket_tool/internal/database"
	"github.com/valyala/fasthttp"
)

//line ../internal/templates/mainpage.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../internal/templates/mainpage.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../internal/templates/mainpage.qtpl:9
type MainPage struct {
	CTX      *fasthttp.RequestCtx
	Data     []Data
	Username string
}
type Data struct {
	database.Bucket
}

//line ../internal/templates/mainpage.qtpl:21
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line ../internal/templates/mainpage.qtpl:21
	qw422016.N().S(`
	This is the main page
`)
//line ../internal/templates/mainpage.qtpl:23
}

//line ../internal/templates/mainpage.qtpl:23
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line ../internal/templates/mainpage.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../internal/templates/mainpage.qtpl:23
	p.StreamTitle(qw422016)
//line ../internal/templates/mainpage.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line ../internal/templates/mainpage.qtpl:23
}

//line ../internal/templates/mainpage.qtpl:23
func (p *MainPage) Title() string {
//line ../internal/templates/mainpage.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line ../internal/templates/mainpage.qtpl:23
	p.WriteTitle(qb422016)
//line ../internal/templates/mainpage.qtpl:23
	qs422016 := string(qb422016.B)
//line ../internal/templates/mainpage.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line ../internal/templates/mainpage.qtpl:23
	return qs422016
//line ../internal/templates/mainpage.qtpl:23
}

//line ../internal/templates/mainpage.qtpl:26
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../internal/templates/mainpage.qtpl:26
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
	<table style="width:100%">
	`)
//line ../internal/templates/mainpage.qtpl:31
	streamemitRows(qw422016, p.Data, p.Username)
//line ../internal/templates/mainpage.qtpl:31
	qw422016.N().S(`
	</table>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
//line ../internal/templates/mainpage.qtpl:36
	qw422016.E().S(p.CTX.RemoteIP().String())
//line ../internal/templates/mainpage.qtpl:36
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
//line ../internal/templates/mainpage.qtpl:37
	qw422016.E().Z(p.CTX.UserAgent())
//line ../internal/templates/mainpage.qtpl:37
	qw422016.N().S(`</b><br/>
	</div>
`)
//line ../internal/templates/mainpage.qtpl:39
}

//line ../internal/templates/mainpage.qtpl:39
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../internal/templates/mainpage.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../internal/templates/mainpage.qtpl:39
	p.StreamBody(qw422016)
//line ../internal/templates/mainpage.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line ../internal/templates/mainpage.qtpl:39
}

//line ../internal/templates/mainpage.qtpl:39
func (p *MainPage) Body() string {
//line ../internal/templates/mainpage.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line ../internal/templates/mainpage.qtpl:39
	p.WriteBody(qb422016)
//line ../internal/templates/mainpage.qtpl:39
	qs422016 := string(qb422016.B)
//line ../internal/templates/mainpage.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line ../internal/templates/mainpage.qtpl:39
	return qs422016
//line ../internal/templates/mainpage.qtpl:39
}

//line ../internal/templates/mainpage.qtpl:41
func streamemitRows(qw422016 *qt422016.Writer, rows []Data, username string) {
//line ../internal/templates/mainpage.qtpl:41
	qw422016.N().S(`
	<tr>
		`)
//line ../internal/templates/mainpage.qtpl:43
	qw422016.N().S(`
		<th>Name</th>
		<th>Map</th>
		<th>Visited</th>
	</tr>

	`)
//line ../internal/templates/mainpage.qtpl:49
	for n, r := range rows {
//line ../internal/templates/mainpage.qtpl:49
		qw422016.N().S(`
		<tr style="background: `)
//line ../internal/templates/mainpage.qtpl:50
		if n&1 == 1 {
//line ../internal/templates/mainpage.qtpl:50
			qw422016.N().S(`white`)
//line ../internal/templates/mainpage.qtpl:50
		} else {
//line ../internal/templates/mainpage.qtpl:50
			qw422016.N().S(`#ddd`)
//line ../internal/templates/mainpage.qtpl:50
		}
//line ../internal/templates/mainpage.qtpl:50
		qw422016.N().S(`">
			`)
//line ../internal/templates/mainpage.qtpl:52
		qw422016.N().S(`
			`)
//line ../internal/templates/mainpage.qtpl:53
		if username != "admin" {
//line ../internal/templates/mainpage.qtpl:53
			qw422016.N().S(`
			<td style="width:20%;">`)
//line ../internal/templates/mainpage.qtpl:54
			qw422016.E().S(r.Placename)
//line ../internal/templates/mainpage.qtpl:54
			qw422016.N().S(`</td> 
			<td style="height:360px; vertical-align:bottom; width:60%;" id="map`)
//line ../internal/templates/mainpage.qtpl:55
			qw422016.N().D(r.Number)
//line ../internal/templates/mainpage.qtpl:55
			qw422016.N().S(`">`)
//line ../internal/templates/mainpage.qtpl:55
			streamdrawMap(qw422016, r.Longitude, r.Latitude, r.Number, r.Placename)
//line ../internal/templates/mainpage.qtpl:55
			qw422016.N().S(`</td>
			<td style="vertical-align:bottom; width:20%;">`)
//line ../internal/templates/mainpage.qtpl:56
			qw422016.N().S(drawButton(r.Visited))
//line ../internal/templates/mainpage.qtpl:56
			qw422016.N().S(`</td>
			`)
//line ../internal/templates/mainpage.qtpl:57
		} else {
//line ../internal/templates/mainpage.qtpl:57
			qw422016.N().S(`
			<td></td>
			<td></td>
			<td><button onclick="myFunction()">Click me!</button></td>
			`)
//line ../internal/templates/mainpage.qtpl:61
		}
//line ../internal/templates/mainpage.qtpl:61
		qw422016.N().S(`
		</tr>
	`)
//line ../internal/templates/mainpage.qtpl:63
	}
//line ../internal/templates/mainpage.qtpl:63
	qw422016.N().S(`
`)
//line ../internal/templates/mainpage.qtpl:64
}

//line ../internal/templates/mainpage.qtpl:64
func writeemitRows(qq422016 qtio422016.Writer, rows []Data, username string) {
//line ../internal/templates/mainpage.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../internal/templates/mainpage.qtpl:64
	streamemitRows(qw422016, rows, username)
//line ../internal/templates/mainpage.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line ../internal/templates/mainpage.qtpl:64
}

//line ../internal/templates/mainpage.qtpl:64
func emitRows(rows []Data, username string) string {
//line ../internal/templates/mainpage.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line ../internal/templates/mainpage.qtpl:64
	writeemitRows(qb422016, rows, username)
//line ../internal/templates/mainpage.qtpl:64
	qs422016 := string(qb422016.B)
//line ../internal/templates/mainpage.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line ../internal/templates/mainpage.qtpl:64
	return qs422016
//line ../internal/templates/mainpage.qtpl:64
}

//line ../internal/templates/mainpage.qtpl:66
func streamdrawMap(qw422016 *qt422016.Writer, lat, long float64, id int, name string) {
//line ../internal/templates/mainpage.qtpl:66
	qw422016.N().S(`
<script >
var map = L.map('map`)
//line ../internal/templates/mainpage.qtpl:68
	qw422016.N().D(id)
//line ../internal/templates/mainpage.qtpl:68
	qw422016.N().S(`', {
    center: [`)
//line ../internal/templates/mainpage.qtpl:69
	qw422016.N().F(long)
//line ../internal/templates/mainpage.qtpl:69
	qw422016.N().S(`, `)
//line ../internal/templates/mainpage.qtpl:69
	qw422016.N().F(lat)
//line ../internal/templates/mainpage.qtpl:69
	qw422016.N().S(`],
    zoom: 13});

L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([`)
//line ../internal/templates/mainpage.qtpl:76
	qw422016.N().F(long)
//line ../internal/templates/mainpage.qtpl:76
	qw422016.N().S(`,`)
//line ../internal/templates/mainpage.qtpl:76
	qw422016.N().F(lat)
//line ../internal/templates/mainpage.qtpl:76
	qw422016.N().S(`]).addTo(map)
    .bindPopup('`)
//line ../internal/templates/mainpage.qtpl:77
	qw422016.E().S(name)
//line ../internal/templates/mainpage.qtpl:77
	qw422016.N().S(`')
    .openPopup();
</script>
`)
//line ../internal/templates/mainpage.qtpl:80
}

//line ../internal/templates/mainpage.qtpl:80
func writedrawMap(qq422016 qtio422016.Writer, lat, long float64, id int, name string) {
//line ../internal/templates/mainpage.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../internal/templates/mainpage.qtpl:80
	streamdrawMap(qw422016, lat, long, id, name)
//line ../internal/templates/mainpage.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line ../internal/templates/mainpage.qtpl:80
}

//line ../internal/templates/mainpage.qtpl:80
func drawMap(lat, long float64, id int, name string) string {
//line ../internal/templates/mainpage.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line ../internal/templates/mainpage.qtpl:80
	writedrawMap(qb422016, lat, long, id, name)
//line ../internal/templates/mainpage.qtpl:80
	qs422016 := string(qb422016.B)
//line ../internal/templates/mainpage.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line ../internal/templates/mainpage.qtpl:80
	return qs422016
//line ../internal/templates/mainpage.qtpl:80
}

//line ../internal/templates/mainpage.qtpl:82
func streamdrawButton(qw422016 *qt422016.Writer, check bool) {
//line ../internal/templates/mainpage.qtpl:82
	qw422016.N().S(`

   `)
//line ../internal/templates/mainpage.qtpl:84
	if check {
//line ../internal/templates/mainpage.qtpl:84
		qw422016.N().S(`
   <input type="checkbox" checked disabled >
   `)
//line ../internal/templates/mainpage.qtpl:86
	} else {
//line ../internal/templates/mainpage.qtpl:86
		qw422016.N().S(`
	<input type="checkbox" disabled >
	`)
//line ../internal/templates/mainpage.qtpl:88
	}
//line ../internal/templates/mainpage.qtpl:88
	qw422016.N().S(`
`)
//line ../internal/templates/mainpage.qtpl:89
}

//line ../internal/templates/mainpage.qtpl:89
func writedrawButton(qq422016 qtio422016.Writer, check bool) {
//line ../internal/templates/mainpage.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../internal/templates/mainpage.qtpl:89
	streamdrawButton(qw422016, check)
//line ../internal/templates/mainpage.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line ../internal/templates/mainpage.qtpl:89
}

//line ../internal/templates/mainpage.qtpl:89
func drawButton(check bool) string {
//line ../internal/templates/mainpage.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line ../internal/templates/mainpage.qtpl:89
	writedrawButton(qb422016, check)
//line ../internal/templates/mainpage.qtpl:89
	qs422016 := string(qb422016.B)
//line ../internal/templates/mainpage.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line ../internal/templates/mainpage.qtpl:89
	return qs422016
//line ../internal/templates/mainpage.qtpl:89
}
